### ISSUE TITLE
Integrate Hungarian fire station data provider

### ISSUE THREAD

**Issue by KAMI911** [KAMI911/osm_poi_matchmaker#116]
Start integration Hungarian Deichmann data provider.
https://www.katasztrofavedelem.hu/33856/tuzoltosagok-elhelyezkedese

Data are available from here:
https://www.katasztrofavedelem.hu/33856/tuzoltosagok-elhelyezkedese

    HTP = Hivatásos Tűzoltó-parancsnokság (1)
    KVŐ = Katasztrófavédelmi Őrs (2)
    ÖTE = Önkéntes Tűzoltó Egyesület (5)
    ÖTP = Önkormányzati Tűzoltó-parancsnokság (3)
    LTP = Létesítményi Tűzoltó-parancsnokság (?)

    fire_station:type=HTP | KVŐ | ÖTE | ÖTP | LTP`?
    
    Angol elnevezésekkel:
    HTP = main_station
    KVŐ = local_station
    ÖTE = voluntary
    ÖTP = municipal
    LTP = concern

**Comment by urbalazs** [comment]
Permission: https://wiki.openstreetmap.org/wiki/File:Katved-adathasznalat-engedely.jpg

**Comment by KAMI911** [comment]
@urbalazs : thanks

**Comment by KAMI911** [comment]
Done, Closing.
