### ISSUE TITLE
Foxpost opening hours: 24/7 + PH off

### ISSUE THREAD

**Issue by vasony** [KAMI911/osm_poi_matchmaker#125]
opening_hours                     MOD 		'24/7'			'24/7; PH off'

according to source data, PH off is wrong, please remove

  "place_id" : 962822,
  "operator_id" : "hu1107",
  "name" : "Bp. 04. ker. Bubbles Tél utca",

  "open" : {
    "hetfo" : "00:00-24:00",
    "kedd" : "00:00-24:00",
    "szerda" : "00:00-24:00",
    "csutortok" : "00:00-24:00",
    "pentek" : "00:00-24:00",
    "szombat" : "00:00-24:00",
    "vasarnap" : "00:00-24:00"
  },

**Comment by urbalazs** [comment]
This is good. The first value is the new value and the second value is the current value in OSM.

**Comment by vasony** [comment]
ok
