### ISSUE TITLE
delete addr:country tag

### ISSUE THREAD

**Issue by vasony** [KAMI911/osm_poi_matchmaker#33]
addr:country is no more needed in addresses, it can be determined from admin boundary polygon

https://wiki.openstreetmap.org/wiki/Key:addr
"May not be required if boundary=administrative is used correctly."

Actions:
- delete addr:country if exists
- don't add it even if exists in source data

**Comment by KAMI911** [comment]
Okay, It can be implemented.
1) First we have to remove addr:country from wiki pages:
https://wiki.openstreetmap.org/wiki/Boltok_gy%C5%B1jtem%C3%A9nye
https://wiki.openstreetmap.org/wiki/T%C3%B6lt%C5%91%C3%A1llom%C3%A1sok_gy%C5%B1jtem%C3%A9nye
https://wiki.openstreetmap.org/wiki/%C3%89ttermek_gy%C5%B1jtem%C3%A9nye
2) Remove addr:country from common database poi_tags.
3) Add logic to delete addr:country during export of OSM files.

**Comment by KAMI911** [comment]
1. First we have to remove addr:country from wiki pages - DONE (/)

**Comment by KAMI911** [comment]
All of three parts are finished. The only thing is I have to do is some testing.

**Comment by KAMI911** [comment]
Tested, OK!
